<?php


/**
 * Implements hook_migrate_api().
 */
function migrate_demo_d2d_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Implements hook_flush_caches().
 */
function migrate_demo_d2d_flush_caches() {
  migrate_demo_d2d_register_migrations();
}

/**
 * Register all D6->D7 migrations.
 */
function migrate_demo_d2d_register_migrations() {
  /**
   * Each migration being registered takes an array of arguments, some required
   * and some optional. Start with the common arguments required by all - the
   * source_connection (connection key, set up in settings.php, pointing to
   * the Drupal 6 database), source_version (major version of Drupal), and
   * group_name (a.k.a. import job).
   */
  $common_arguments = array(
    'source_connection' => 'legacy',
    'source_version' => 6,
  );

  $common_arguments['group_name'] = 'Users and Roles';

  /*** Roles ***/
  $role_arguments = $common_arguments + array(
      'machine_name' => 'Role',
      'description' => t('Import Drupal 6 roles'),
      'role_mappings' => array(
        'webmaster' => 'builder',
        'editor' => 'editor',
        'avc' => 'avc',
        'reviewer' => 'reviewer',
        'web assistant' => 'web assistant',

      ),
    );
  Migration::registerMigration('DrupalRole6Migration',
    $role_arguments['machine_name'], $role_arguments);

  /*** Users ***/
  $arguments = $common_arguments + array(
      'description' => t('Migration of users from HRWeb Drupal 6'),
      'machine_name' => 'User',
      'role_migration' => 'Role',
    );

  Migration::registerMigration('DrupalUser6Migration', $arguments['machine_name'],
    $arguments);


}

