$data = array(
  'bundles' => array(
    'faqs' => (object) array(
      'vid' => '4',
      'name' => 'FAQs',
      'machine_name' => 'faqs',
      'description' => 'Categories for Frequently Asked Questions.',
      'hierarchy' => '0',
      'module' => 'taxonomy',
      'weight' => '0',
      'bc_entity_type' => 'taxonomy_term',
    ),
    'glossary' => (object) array(
      'vid' => '5',
      'name' => 'Glossary',
      'machine_name' => 'glossary',
      'description' => '',
      'hierarchy' => '0',
      'module' => 'taxonomy',
      'weight' => '0',
      'bc_entity_type' => 'taxonomy_term',
    ),
    'news_item' => (object) array(
      'vid' => '8',
      'name' => 'News Item',
      'machine_name' => 'news_item',
      'description' => '',
      'hierarchy' => '0',
      'module' => 'taxonomy',
      'weight' => '0',
      'bc_entity_type' => 'taxonomy_term',
    ),
    'primary_navigation_section' => (object) array(
      'vid' => '6',
      'name' => 'Primary Navigation Section',
      'machine_name' => 'primary_navigation_section',
      'description' => '',
      'hierarchy' => '0',
      'module' => 'taxonomy',
      'weight' => '0',
      'bc_entity_type' => 'taxonomy_term',
    ),
    'related_links_categories' => (object) array(
      'vid' => '9',
      'name' => 'Related Links Categories',
      'machine_name' => 'related_links_categories',
      'description' => '',
      'hierarchy' => '0',
      'module' => 'taxonomy',
      'weight' => '0',
      'bc_entity_type' => 'taxonomy_term',
    ),
    'secondary_navigation_section' => (object) array(
      'vid' => '7',
      'name' => 'Secondary Navigation Section',
      'machine_name' => 'secondary_navigation_section',
      'description' => '',
      'hierarchy' => '0',
      'module' => 'taxonomy',
      'weight' => '0',
      'bc_entity_type' => 'taxonomy_term',
    ),
  ),
  'instances' => array(),
);
